import { ChartColors } from "../chartcolors.slint";
import { Theme } from "../theme.slint";
import { VerticalBox, ListView } from "std-widgets.slint";
import { PieChartData } from "../piechart.slint";
import { Background } from "../background.slint";

global ChartBase {
    in property <string> base : " M 100, 100 m 100, 0 a 100,100 0 1,0 -200,0 a 100,100 0 1,0  200,0 ";
}

component RamChart inherits Rectangle {
    in property <string> data;
    in property <PieChartData> ram-pie-chart;
    Path {
        viewbox-width: 190;
        viewbox-height: -100;
        commands: "M 0 0 M 190 0 M 0 -100 M 190 -100 " + data;
        stroke-width: 2px;
        stroke: ChartColors.colors[5];
    }
    Path {
        viewbox-width: 190;
        viewbox-height: -100;
        commands: "M 0 0 M 190 0 M 0 -10 L 190 -10 M 0 -20 L 190 -20 M 0 -30 L 190 -30 M 0 -40 L 190 -40 M 0 -50 L 190 -50 M 0 -60 L 190 -60 M 0 -70 L 190 -70 M 0 -80 L 190 -80 M 0 -90 L 190 -90 M 0 -100 M 190 -100";
        stroke: Theme.palette.chart-lines;
        stroke-width: 2px;
    }
}

component PieChartWidget inherits VerticalLayout {
    in property <PieChartData> pie-chart-data;
    in property <string> title;
    private property <int> sector: pie-chart-data.percentage > 50.0 ? 1 : 0;
    in property <brush> circle-color;
    in property <brush> indicator-color;

    Rectangle {
        width: 20px;
        height: 20px;
    }
    Text {
        text: title;
        color: white;
        font-size: 16px;
    }
    Rectangle {
        height: 12px;
    }
    Rectangle {
        height: 100%;
        width: 100%;
        Path {
            height: 100%;
            width: 100%;
            commands: ChartBase.base;
            stroke: circle-color;
            stroke-width: 20px;
            viewbox-width: 200;
            viewbox-height: 200;
        }
        Path {
            height: 100%;
            width: 100%;
            commands: "M 200 100 A 100 100 0 \{sector} 1 \{pie-chart-data.angleX} \{pie-chart-data.angleY}";
            stroke: indicator-color;
            stroke-width: 20px;
            viewbox-width: 200;
            viewbox-height: 200;
        }
        Text {
            color: white;
            text: pie-chart-data.percentage + "%";
            font-size: 16px;
        }
    }    
}

export component RamWidget inherits VerticalLayout {
    in property <string> data;
    in property <PieChartData> ram-pie-chart;
    in property <PieChartData> swap-pie-chart;
    padding: 25px;
    alignment: LayoutAlignment.start;
    HorizontalLayout {
            Rectangle {
                width: 70%;
                height: self.width / 1.9;
                background: Theme.palette.chart-gradient;
                border-radius: 15px; 
                clip: true;
                RamChart {
                    width: 100%;
                    height: 100%;
                    x: 0;
                    data: data;
                }
            } 
    }  

    HorizontalLayout {
        width: 100%;
        height: 30%;
        PieChartWidget {
            pie-chart-data: ram-pie-chart;
            circle-color: Theme.palette.turquoise-linear-gradient;
            indicator-color: Theme.palette.turquoise-chart-indicator;
            title: "Used memory:";
            height: 100%;
            width: 30%;
            alignment: LayoutAlignment.center;
        }
        Rectangle {
            width: 20px;
        }
        PieChartWidget {
            pie-chart-data: swap-pie-chart;
            circle-color: Theme.palette.green-linear-gradient;
            indicator-color: Theme.palette.green-chart-indicator;
            title: "Used swap:";
            height: 100%;
            width: 30%;
            alignment: LayoutAlignment.center;
        }    
    }
}