import { Tab } from "../navbar/tabs.slint";
import { TabWidget } from "std-widgets.slint";

export component Body inherits VerticalLayout { 
    in property <Tab> selected-tab;
    padding-left: 24px;
    padding-top: 64px;
    Text {
        // width: 100%;
        max-height: 100px;
        text: selected-tab.name;
        font-family: "Raleway";
        font-size: 30px;
        font-weight: 700;
        horizontal-alignment: left;
        vertical-alignment: top;
        letter-spacing: 0px;
        color: #ffffffff;
        overflow: TextOverflow.elide;
    }

    VerticalLayout {
        width: 100%;
        padding-top: 25px;
        padding-right: 25px;
        padding-bottom: 25px;
        Rectangle {
            x: 0px;
            background: #2d313b99;
            border-radius: 30px;
        }
    }
    
    
    // Rectangle { height: 0%; }
}