import { Logo } from "navbar/logo.slint";
import { Title } from "navbar/title.slint";
import { Tab, TabsExtended } from "tabs.slint";
import { Theme } from "theme.slint";

component TabText inherits Text {
    font-family: "Rubik";
    font-size: 16px;
    font-weight: 400;
    horizontal-alignment: center;
    vertical-alignment: center;
    letter-spacing: 0px;
    color: #ffffffff;
    animate color { duration: Theme.durations.fast; }
}

component TabWidget inherits VerticalLayout {
    callback tabselect();
    in property <Tab> tab;
    in property <Tab> selected-tab;
    in property <bool> active: tab == selected-tab;
    
    Rectangle { /* Rectangle 1 */
        width: 100%;
        height: 75px;
        border-radius: 16px;
        background: Theme.palette.transparent;
        // 
        TabText { /* Dashboard */
            text: tab.name;
            color: active? Theme.palette.left-tab-text : Theme.palette.inactive-text;
        }
        TouchArea {
            clicked => {tabselect()}
            mouse-cursor: MouseCursor.pointer;
        }
    }
}

component TabSelector inherits Rectangle {
    in property <Tab> selected-tab;
    y: selected-tab.position;
    animate y { duration: Theme.durations.fast; }
}

export component LeftNavBar inherits Rectangle { 
    in-out property <Tab> selected-tab;
    callback select-tab(Tab);
    VerticalLayout {
        padding-top: 46px;
        padding-left: 34px;
        padding-bottom: 100px;
        HorizontalLayout {
            Logo {  }
            Title {  }
        }

        TabWidget {
            padding-top: 48px;
            tab: TabsExtended.cpu-tab;
            selected-tab: selected-tab;
            tabselect => {
                select-tab(self.tab)
            }
        }
        TabWidget {
            padding-top: 12px;
            tab: TabsExtended.ram-tab;
            selected-tab: selected-tab;
            tabselect => {
                select-tab(self.tab)
            }
        }
        TabWidget {
            padding-top: 12px;
            tab: TabsExtended.temp-tab;
            selected-tab: selected-tab;
            tabselect => {
                select-tab(self.tab)
            }
        }
        TabWidget {
            padding-top: 12px;
            tab: TabsExtended.gpu-tab;
            selected-tab: selected-tab;
            tabselect => {
                select-tab(self.tab)
            }
        }
        TabWidget {
            padding-top: 12px;
            tab: TabsExtended.stor-tab;
            selected-tab: selected-tab;
            tabselect => {
                select-tab(self.tab)
            }
        }
        Rectangle {}
    }
    TabSelector {
        x: 0px;
        selected-tab: selected-tab;
        width: 100%;
        height: 75px;
        border-radius: 16px;
        background: Theme.palette.tab-gradient;
    }
}