import { Theme } from "theme.slint";

export component Spotlights {
    Rectangle { /* Group 1 */
        width: 2215px;
        height: 1819px;
        x: -374px;
        y: -453px;
        Path { /* Ellipse 2 */
            width: 462px;
            height: 462px;
            x: 17px;
            y: 306px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.turquoise_gradient;
        }
        Path { /* Ellipse 1 */
            width: 462px;
            height: 462px;
            x: 51px;
            y: 102px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.gray-gradient;
        }
        Path { /* Ellipse 5 */
            width: 462px;
            height: 462px;
            x: 1719px;
            y: 1327px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.turquoise_gradient;
        }
        Path { /* Ellipse 6 */
            width: 462px;
            height: 462px;
            x: 1753px;
            y: 1123px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.gray-gradient;
        }
        Path { /* Ellipse 7 */
            width: 462px;
            height: 462px;
            x: 0px;
            y: 1357px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.turquoise_gradient;
        }
        Path { /* Ellipse 8 */
            width: 462px;
            height: 462px;
            x: 34px;
            y: 1153px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.gray-gradient;
        }
        Path { /* Ellipse 3 */
            width: 462px;
            height: 462px;
            x: 1644px;
            y: 190px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.turquoise_gradient;
        }
        Path { /* Ellipse 4 */
            width: 462px;
            height: 462px;
            x: 1671px;
            y: 0px;
            commands: "M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z";
            fill-rule: nonzero;
            stroke-width: 1px;
            fill: Theme.palette.gray-gradient;
        }
    }
}