export struct Palette {
    main-background: brush,
    snakes-color: brush,

    // gradients
    turquoise_gradient: brush,
    gray-gradient: brush
}

export struct Spaces {
    small: length,
    medium: length,
    large: length,
}

export struct Durations {
    fast: duration,
    medium: duration,
    slow: duration,
}

struct Font {
    size: length,
    weight: float,
}

export struct Typo {
    label: Font,
    label-light: Font,
    header: Font,
    header-item: Font,
    header-item-light: Font,
    value: Font,
    desciption: Font,
    desciption-light: Font,
    value-big: Font,
}

export global Theme {
    in property <Palette> palette: {
        main-background: #22262fff,
        snakes-color: #ffffff0D,

        // gradients
        turquoise_gradient: @radial-gradient(circle, #11bca94D 0%, #00000000 100%),
        gray-gradient: @radial-gradient(circle, #414b634D 0%, #00000000 100%)
    };

    in property <Spaces> spaces: {
        small: 5px,
        medium: 10px,
        large: 20px,
    };

    in property <Durations> durations: {
        fast: 125ms,
        medium: 200ms,
        slow: 500ms,
    };

    in property <Typo> typo: {
        label-light: {
            size: 12px,
            weight: 400
        },
        label: {
            size: 12px,
            weight: 500
        },
        header: {
            size: 16px,
            weight: 600
        },
        header-item: {
            size: 18px,
            weight: 400
        },
        header-item-light: {
            size: 18px,
            weight: 200
        },
        value: {
            size: 26px,
            weight: 500
        },
        desciption: {
            size: 14px,
            weight: 400
        },
        desciption-light: {
            size: 14px,
            weight: 200
        },
        value-big: {
            size: 40px,
            weight: 200
        },
    };
}