export struct Palette {
    main-background: brush,
    snakes-color: brush,
    left-tab-text: brush,
    inactive-text: brush,
    transparent: brush,
    chart-background: brush,
    chart-lines: brush,

    // gradients
    turquoise_gradient: brush,
    gray-gradient: brush,
    tab-gradient: brush,
    chart-gradient: brush
}

export struct Spaces {
    small: length,
    medium: length,
    large: length,
}

export struct Durations {
    fast: duration,
    medium: duration,
    slow: duration,
}

struct Font {
    size: length,
    weight: float,
}

export struct Typo {
    label: Font,
    label-light: Font,
    header: Font,
    header-item: Font,
    header-item-light: Font,
    value: Font,
    desciption: Font,
    desciption-light: Font,
    value-big: Font,
}

export global Theme {
    in property <Palette> palette: {
        main-background: #22262fff,
        snakes-color: #ffffff0D,
        left-tab-text: #ffffff,
        inactive-text: #8b8c91,
        transparent: #00000000,
        chart-background: #00000036,
        chart-lines: #ffffff36,

        // gradients
        turquoise_gradient: @radial-gradient(circle, #11bca94D 0%, #00000000 100%),
        gray-gradient: @radial-gradient(circle, #414b634D 0%, #00000000 100%),
        tab-gradient: @linear-gradient(-92.25084deg, #ffffff36 0, #ffffff00 1),
        chart-gradient: @linear-gradient(185deg, #11bca822 0, #0000004e 1)
    };

    in property <Spaces> spaces: {
        small: 5px,
        medium: 10px,
        large: 20px,
    };

    in property <Durations> durations: {
        fast: 125ms,
        medium: 200ms,
        slow: 500ms,
    };

    in property <Typo> typo: {
        label-light: {
            size: 12px,
            weight: 400
        },
        label: {
            size: 12px,
            weight: 500
        },
        header: {
            size: 16px,
            weight: 600
        },
        header-item: {
            size: 18px,
            weight: 400
        },
        header-item-light: {
            size: 18px,
            weight: 200
        },
        value: {
            size: 26px,
            weight: 500
        },
        desciption: {
            size: 14px,
            weight: 400
        },
        desciption-light: {
            size: 14px,
            weight: 200
        },
        value-big: {
            size: 40px,
            weight: 200
        },
    };
}