export component Logo inherits HorizontalLayout {
    VerticalLayout {
        width: 15px;
        height: 50px;
        padding-top: 23px;
        Rectangle {
            width: 5px;
            height: 27px;
            background: #cf2458ff;
        }
    }
    VerticalLayout {
        width: 15px;
        height: 50px;
        padding-top: 10px;
        Rectangle {
            width: 5px;
            height: 40px;
            background: #10bca8ff;
        }
    }        
    Rectangle { /* Line 1 */
        width: 5px;
        height: 50px;
        background: #f3bc72ff;
    }
}