export component Title inherits VerticalLayout {
    width: 100%;
    padding-left: 24px;
    Text {
        text: "SMT";
        font-family: "Raleway";
        font-size: 25px;
        font-weight: 700;
        horizontal-alignment: left;
        vertical-alignment: top;
        letter-spacing: 0px;
        color: #ffffffff;
    }
    Text {
        text: "System metrics tracker";
        font-family: "Raleway";
        font-size: 12.5px;
        font-weight: 400;
        horizontal-alignment: left;
        vertical-alignment: top;
        letter-spacing: 0px;
        color: #ffffffff;
    }
}